### PR TITLE
Code to conduct

### PR DESCRIPTION
**Pull request by Moathal**
- Completed README file and added all necessary things in it.
- Added an index.html with h1 Containing "Hello microvers!".
- Added a style file and linked it in the html.
- Made the desired formatting changes in the previous pull request.

### CODE REVIEW

**Comment by Moathal** [comment]
- Completed README file and added all necessary things in it.
- Added an index.html with h1 Containing "Hello microvers!".
- Added a style file and linked it in the html.
- Fixed css formatting problem.

**Comment by Moathal** [comment]
- Completed README file and added all necessary things in it.
- Added an index.html with h1 Containing "Hello microvers!".
- Added a style file and linked it in the html.
- Fixed css formatting problem.

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @Moathal  :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

You have done a tremendous job setting up your hello Microverse project :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions
 
 - [OPTIONAL] - Kindly make sure to include an MIT.md in your project. If you may be in doubt, have a look at [this](https://github.com/microverseinc/readme-template/blob/master/MIT.md) example MIT.md this way your documentation will be 100% complete :sunglasses: . 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Moathal** [comment]
- Followed up with you optional request and it is all done

**Pull request merged**
